# HTTP Server
server:  
  port: 3340   # HTTP port

# Spring properties
spring:  
  application:
    name: microservice-client

logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
    
app:
  serviceurl: http://localhost:8080/login/cas
  serviceticketvalidator: https://sso.dreamgenics.com/cas
  serviceauthenticationentrypoint: https://sso.dreamgenics.com/cas/login
  
  
