# HTTP Server
server:  
  port: 3340   # HTTP port

# Spring properties
spring:  
  application:
    name: microservice-projectmanagement
    
mybatis:
  config-location: classpath:mybatis-config.xml
